version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    volumes: 
      - ${PWD}/loki-conf.yml:/etc/loki-conf.yml
    command: -config.file=/etc/loki-conf.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - ${PWD}/promtail-conf.yml:/etc/promtail-conf.yml
    command: -config.file=/etc/promtail-conf.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki